# <u>Data Cleaning</u>
## 1st Dataset

In [7]:
# Import libraries
import pandas as pd
import numpy as np

# Load dataset
fund_master = pd.read_csv("../data/raw/01_fund_master.csv")

fund_master.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [8]:
fund_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [9]:
fund_master.describe(include="all")

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
count,40.000000,40,40,40,40,40,40,40,40.000000,40.000000,40.0,40.000000,40,40,40
unique,NaN,10,40,2,12,2,34,10,NaN,NaN,NaN,NaN,29,5,9
top,NaN,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2013-01-01,NIFTY 100 TRI,NaN,NaN,NaN,NaN,Sohini Andani,Moderate,EC01
freq,NaN,5,1,34,14,32,7,14,NaN,NaN,NaN,NaN,2,16,14
mean,120247.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.237000,0.812500,500.0,1277.500000,NaN,NaN,NaN
std,14534.998667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.386584,0.387091,0.0,1082.847031,NaN,NaN,NaN
min,100016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.550000,0.000000,500.0,100.000000,NaN,NaN,NaN
25%,118632.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.787500,1.000000,500.0,1000.000000,NaN,NaN,NaN
50%,119551.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.425000,1.000000,500.0,1000.000000,NaN,NaN,NaN
75%,120842.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.540000,1.000000,500.0,1000.000000,NaN,NaN,NaN
max,149324.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.640000,1.000000,500.0,5000.000000,NaN,NaN,NaN

In [10]:
fund_master.isnull().sum()

amfi_code             0
fund_house            0
scheme_name           0
category              0
sub_category          0
plan                  0
launch_date           0
benchmark             0
expense_ratio_pct     0
exit_load_pct         0
min_sip_amount        0
min_lumpsum_amount    0
fund_manager          0
risk_category         0
sebi_category_code    0
dtype: int64

In [11]:
fund_master.duplicated().sum()

np.int64(0)

In [12]:
fund_master.dtypes

amfi_code               int64
fund_house                str
scheme_name               str
category                  str
sub_category              str
plan                      str
launch_date               str
benchmark                 str
expense_ratio_pct     float64
exit_load_pct         float64
min_sip_amount          int64
min_lumpsum_amount      int64
fund_manager              str
risk_category             str
sebi_category_code        str
dtype: object

In [36]:
# Launch_date column is in string format, we need to convert it to datetime format
fund_master["launch_date"] = pd.to_datetime(fund_master["launch_date"], format="%Y-%m-%d")
print(fund_master["launch_date"].dtype)

datetime64[us]

In [46]:
fund_master.to_csv("../data/processed/01_fund_master_cleaned.csv", index=False)

## 2nd Dataset

In [37]:
import pandas as pd
nav_history = pd.read_csv("../data/raw/02_nav_history.csv")
nav_history.info()

<class 'pandas.DataFrame'>
RangeIndex: 46000 entries, 0 to 45999
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   amfi_code  46000 non-null  int64
 1   date       46000 non-null  str
 2   nav        46000 non-null  float64
dtypes: float64(1), int64(1), str(1)
memory usage: 1.1 MB

In [38]:
nav_history.describe(include="all")

            amfi_code        date           nav
count    46000.000000       46000  46000.000000
unique            NaN        1150           NaN
top               NaN  2022-01-03           NaN
freq              NaN          40           NaN
mean    120247.000000         NaN    269.570265
std      14352.317221         NaN    577.187060
min     100016.000000         NaN     26.136600
25%     118632.750000         NaN     69.170425
50%     119551.500000         NaN    122.732150
75%     120842.250000         NaN    260.338675
max     149324.000000         NaN   4268.549700

In [39]:
nav_history.isnull().sum()

amfi_code    0
date         0
nav          0
dtype: int64

In [40]:
nav_history.dtypes

amfi_code      int64
date             str
nav          float64
dtype: object

In [41]:
nav_history.duplicated().sum()

np.int64(0)

In [42]:
# Date is in string format, we need to convert it to datetime format
nav_history["date"] = pd.to_datetime(nav_history["date"])
print(nav_history["date"].dtype)

datetime64[us]

In [43]:
nav_history.sort_values(by=["amfi_code", "date"])
nav_history.head()

   amfi_code       date      nav
0     119551 2022-01-03  54.3856
1     119551 2022-01-04  54.3474
2     119551 2022-01-05  54.6869
3     119551 2022-01-06  55.4550
4     119551 2022-01-07  55.3692

In [44]:
if nav_history["nav"].isnull().sum() > 0:
    nav_history["nav"] = nav_history.groupby("amfi_code")["nav"].ffill()
print("Missing NAV values after forward fill:", nav_history["nav"].isnull().sum())

Missing NAV values after forward fill: 0

In [45]:
#validate NAV > 0
print((nav_history["nav"] <= 0).sum())

0

In [47]:
nav_history.to_csv("../data/processed/02_nav_history_cleaned.csv", index=False)

## 3rd Dataset

In [48]:
aum_by_fund_house = pd.read_csv("../data/raw/03_aum_by_fund_house.csv")
aum_by_fund_house.info()

<class 'pandas.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            90 non-null     str
 1   fund_house      90 non-null     str
 2   aum_lakh_crore  90 non-null     float64
 3   aum_crore       90 non-null     int64
 4   num_schemes     90 non-null     int64
dtypes: float64(1), int64(2), str(2)
memory usage: 3.6 KB

In [49]:
aum_by_fund_house.head()

         date           fund_house  aum_lakh_crore  aum_crore  num_schemes
0  2022-03-31      SBI Mutual Fund            6.05     605000          186
1  2022-03-31  ICICI Prudential MF            4.65     465000          216
2  2022-03-31     HDFC Mutual Fund            4.35     435000          195
3  2022-03-31      Nippon India MF            2.70     270000          177
4  2022-03-31    Kotak Mahindra MF            2.70     270000          168

In [51]:
aum_by_fund_house.isnull().sum()

date              0
fund_house        0
aum_lakh_crore    0
aum_crore         0
num_schemes       0
dtype: int64

In [52]:
aum_by_fund_house.duplicated().sum()

np.int64(0)

In [53]:
aum_by_fund_house.dtypes

date                  str
fund_house            str
aum_lakh_crore    float64
aum_crore           int64
num_schemes         int64
dtype: object

In [54]:
aum_by_fund_house["date"] = pd.to_datetime(aum_by_fund_house["date"])

In [68]:
aum_by_fund_house.to_csv("../data/processed/03_aum_by_fund_house_cleaned.csv", index=False)

## 4th Dataset

In [57]:
monthly_sip=pd.read_csv("../data/raw/04_monthly_sip_inflows.csv")
monthly_sip.info()

<class 'pandas.DataFrame'>
RangeIndex: 48 entries, 0 to 47
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   month                      48 non-null     str
 1   sip_inflow_crore           48 non-null     int64
 2   active_sip_accounts_crore  48 non-null     float64
 3   new_sip_accounts_lakh      48 non-null     float64
 4   sip_aum_lakh_crore         48 non-null     float64
 5   yoy_growth_pct             36 non-null     float64
dtypes: float64(4), int64(1), str(1)
memory usage: 2.4 KB

In [59]:
monthly_sip.head()

,month,sip_inflow_crore,active_sip_accounts_crore,new_sip_accounts_lakh,sip_aum_lakh_crore,yoy_growth_pct
0,2022-01,11517,4.91,9.10,4.80,NaN
1,2022-02,11438,4.93,8.20,4.85,NaN
2,2022-03,12328,5.09,10.50,5.01,NaN
3,2022-04,11863,5.48,9.52,5.12,NaN
4,2022-05,12286,5.55,8.10,5.15,NaN

In [62]:
monthly_sip.isnull().sum()

month                         0
sip_inflow_crore              0
active_sip_accounts_crore     0
new_sip_accounts_lakh         0
sip_aum_lakh_crore            0
yoy_growth_pct               12
dtype: int64

In [63]:
monthly_sip.duplicated().sum()

np.int64(0)

In [65]:
# fix month type
monthly_sip["month"] = pd.to_datetime(monthly_sip["month"], format="%Y-%m")
# yoy_growth has 12 missing values because there is no previous year data.
# No cleaning is required for this column. We will keep it as it is.

In [67]:
monthly_sip.to_csv("../data/processed/04_monthly_sip_inflows_cleaned.csv", index=False)

## 5th Dataset

In [70]:
category_inflows = pd.read_csv("../data/raw/05_category_inflows.csv")
category_inflows.info()

<class 'pandas.DataFrame'>
RangeIndex: 144 entries, 0 to 143
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   month             144 non-null    str
 1   category          144 non-null    str
 2   net_inflow_crore  144 non-null    float64
dtypes: float64(1), str(2)
memory usage: 3.5 KB

In [72]:
category_inflows.isnull().sum()

month               0
category            0
net_inflow_crore    0
dtype: int64

In [73]:
category_inflows.duplicated().sum()

np.int64(0)

In [75]:
category_inflows["month"] = pd.to_datetime(category_inflows["month"], format="%Y-%m")
print(category_inflows["month"].dtype)

datetime64[us]

In [76]:
category_inflows.to_csv("../data/processed/05_category_inflows_cleaned.csv", index=False)

## 6th Dataset

In [78]:
industry_folio_count = pd.read_csv("../data/raw/06_industry_folio_count.csv")
industry_folio_count.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                21 non-null     str
 1   total_folios_crore   21 non-null     float64
 2   equity_folios_crore  21 non-null     float64
 3   debt_folios_crore    21 non-null     float64
 4   hybrid_folios_crore  21 non-null     float64
 5   others_folios_crore  21 non-null     float64
dtypes: float64(5), str(1)
memory usage: 1.1 KB

In [79]:
industry_folio_count.isnull().sum()

month                  0
total_folios_crore     0
equity_folios_crore    0
debt_folios_crore      0
hybrid_folios_crore    0
others_folios_crore    0
dtype: int64

In [80]:
industry_folio_count.duplicated().sum()

np.int64(0)

In [81]:
industry_folio_count.to_csv("../data/processed/06_industry_folio_count_cleaned.csv", index=False)

## 7th Dataset

In [82]:
scheme_performance = pd.read_csv("../data/raw/07_scheme_performance.csv")
scheme_performance.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   scheme_name         40 non-null     str
 2   fund_house          40 non-null     str
 3   category            40 non-null     str
 4   plan                40 non-null     str
 5   return_1yr_pct      40 non-null     float64
 6   return_3yr_pct      40 non-null     float64
 7   return_5yr_pct      40 non-null     float64
 8   benchmark_3yr_pct   40 non-null     float64
 9   alpha               40 non-null     float64
 10  beta                40 non-null     float64
 11  sharpe_ratio        40 non-null     float64
 12  sortino_ratio       40 non-null     float64
 13  std_dev_ann_pct     40 non-null     float64
 14  max_drawdown_pct    40 non-null     float64
 15  aum_crore           40 non-null     int64
 16  expense_ratio_pct   40 non-null     float64
 17  morningstar_rating  40 non-null     int64
 18  risk_grade          40 non-null     str
dtypes: float64(11), int64(3), str(5)
memory usage: 6.1 KB

In [83]:
scheme_performance.isnull().sum()

amfi_code             0
scheme_name           0
fund_house            0
category              0
plan                  0
return_1yr_pct        0
return_3yr_pct        0
return_5yr_pct        0
benchmark_3yr_pct     0
alpha                 0
beta                  0
sharpe_ratio          0
sortino_ratio         0
std_dev_ann_pct       0
max_drawdown_pct      0
aum_crore             0
expense_ratio_pct     0
morningstar_rating    0
risk_grade            0
dtype: int64

In [84]:
scheme_performance.duplicated().sum()

np.int64(0)

In [89]:
# Validate return values are numeric
scheme_performance[["return_1yr_pct","return_3yr_pct","return_5yr_pct","benchmark_3yr_pct"]].dtypes
# Return values are already in numeric format, no further cleaning is required.
# We can also check for any invalid return values (non-numeric) and handle them if necessary. However, since the return values are already in numeric format, we can skip this step.
#  return_cols = [
#     "return_1yr_pct",
#     "return_3yr_pct",
#     "return_5yr_pct",
#     "benchmark_3yr_pct"
# ]

# for col in return_cols:
#     scheme_performance[col] = pd.to_numeric(scheme_performance[col], errors="coerce")

# invalid = scheme_performance[scheme_performance[return_cols].isna().any(axis=1)]

return_1yr_pct       float64
return_3yr_pct       float64
return_5yr_pct       float64
benchmark_3yr_pct    float64
dtype: object

In [90]:
#flag anomalies in return values
anomalies = scheme_performance[(scheme_performance["return_1yr_pct"] < -100) | (scheme_performance["return_1yr_pct"] > 100) |
                               (scheme_performance["return_3yr_pct"] < -100) | (scheme_performance["return_3yr_pct"] > 100) |
                               (scheme_performance["return_5yr_pct"] < -100) | (scheme_performance["return_5yr_pct"] > 100) |
                               (scheme_performance["benchmark_3yr_pct"] < -100) | (scheme_performance["benchmark_3yr_pct"] > 100)]

print("Number of anomalies in return values:",anomalies)

Number of anomalies in return values: Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []

In [94]:
# check expense_ratio range (0.1% – 2.5%).
invalid_expense_ratio = scheme_performance[(scheme_performance["expense_ratio_pct"] < 0.1) | (scheme_performance["expense_ratio_pct"] > 2.5)]
print("Number of invalid expense ratios:",invalid_expense_ratio)
print("Number of invalid expense ratios:",invalid_expense_ratio.shape[0])
print("Number of invalid expense ratios:",len(invalid_expense_ratio))

Number of invalid expense ratios: Empty DataFrame
Columns: [amfi_code, scheme_name, fund_house, category, plan, return_1yr_pct, return_3yr_pct, return_5yr_pct, benchmark_3yr_pct, alpha, beta, sharpe_ratio, sortino_ratio, std_dev_ann_pct, max_drawdown_pct, aum_crore, expense_ratio_pct, morningstar_rating, risk_grade]
Index: []
Number of invalid expense ratios: 0
Number of invalid expense ratios: 0

In [96]:
scheme_performance.to_csv("../data/processed/07_scheme_performance_cleaned.csv", index=False)

## 8th Dataset

In [97]:
investor_transactions = pd.read_csv("../data/raw/08_investor_transactions.csv")
investor_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 32778 entries, 0 to 32777
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   investor_id         32778 non-null  str
 1   transaction_date    32778 non-null  str
 2   amfi_code           32778 non-null  int64
 3   transaction_type    32778 non-null  str
 4   amount_inr          32778 non-null  int64
 5   state               32778 non-null  str
 6   city                32778 non-null  str
 7   city_tier           32778 non-null  str
 8   age_group           32778 non-null  str
 9   gender              32778 non-null  str
 10  annual_income_lakh  32778 non-null  float64
 11  payment_mode        32778 non-null  str
 12  kyc_status          32778 non-null  str
dtypes: float64(1), int64(2), str(10)
memory usage: 3.3 MB

In [100]:
investor_transactions.isnull().sum()

investor_id           0
transaction_date      0
amfi_code             0
transaction_type      0
amount_inr            0
state                 0
city                  0
city_tier             0
age_group             0
gender                0
annual_income_lakh    0
payment_mode          0
kyc_status            0
dtype: int64

In [101]:
investor_transactions.duplicated().sum()

np.int64(0)

In [102]:
investor_transactions.columns

Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

In [103]:
investor_transactions["transaction_date"] = pd.to_datetime(investor_transactions["transaction_date"], format="%Y-%m-%d")

In [104]:
investor_transactions["transaction_type"].unique()

<StringArray>
['SIP', 'Redemption', 'Lumpsum']
Length: 3, dtype: str

In [105]:
(investor_transactions["amount_inr"] < 0).sum()

np.int64(0)

In [106]:
investor_transactions["kyc_status"].unique()

<StringArray>
['Verified', 'Pending']
Length: 2, dtype: str

In [108]:
investor_transactions.to_csv("../data/processed/08_investor_transactions_cleaned.csv", index=False)

## 9th Dataset

In [109]:
portfolio_holdings = pd.read_csv("../data/raw/09_portfolio_holdings.csv")
portfolio_holdings.info()

<class 'pandas.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   amfi_code          322 non-null    int64
 1   stock_symbol       322 non-null    str
 2   stock_name         322 non-null    str
 3   sector             322 non-null    str
 4   weight_pct         322 non-null    float64
 5   market_value_cr    322 non-null    float64
 6   current_price_inr  322 non-null    float64
 7   portfolio_date     322 non-null    str
dtypes: float64(3), int64(1), str(4)
memory usage: 20.3 KB

In [110]:
portfolio_holdings["portfolio_date"] = pd.to_datetime(portfolio_holdings["portfolio_date"], format="%Y-%m-%d")

In [111]:
portfolio_holdings.isnull().sum()

amfi_code            0
stock_symbol         0
stock_name           0
sector               0
weight_pct           0
market_value_cr      0
current_price_inr    0
portfolio_date       0
dtype: int64

In [112]:
portfolio_holdings.duplicated().sum()

np.int64(0)

In [114]:
portfolio_holdings.to_csv("../data/processed/09_portfolio_holdings_cleaned.csv", index=False)

## 10th Dataset

In [115]:
benchmark_indices = pd.read_csv("../data/raw/10_benchmark_indices.csv")
benchmark_indices.info()

<class 'pandas.DataFrame'>
RangeIndex: 8050 entries, 0 to 8049
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         8050 non-null   str
 1   index_name   8050 non-null   str
 2   close_value  8050 non-null   float64
dtypes: float64(1), str(2)
memory usage: 188.8 KB

In [116]:
benchmark_indices.isnull().sum()

date           0
index_name     0
close_value    0
dtype: int64

In [119]:
benchmark_indices.duplicated().sum()

np.int64(0)

In [120]:
benchmark_indices["date"] = pd.to_datetime(benchmark_indices["date"], format="%Y-%m-%d")

In [121]:
benchmark_indices.to_csv

<bound method NDFrame.to_csv of            date   index_name  close_value
0    2022-01-03      NIFTY50     17492.79
1    2022-01-04      NIFTY50     17689.64
2    2022-01-05      NIFTY50     17835.05
3    2022-01-06      NIFTY50     17878.51
4    2022-01-07      NIFTY50     17759.15
...         ...          ...          ...
8045 2026-05-25  CRISIL_GILT      2278.26
8046 2026-05-26  CRISIL_GILT      2281.42
8047 2026-05-27  CRISIL_GILT      2281.30
8048 2026-05-28  CRISIL_GILT      2298.35
8049 2026-05-29  CRISIL_GILT      2302.79

[8050 rows x 3 columns]>

In [123]:
benchmark_indices.to_csv("../data/processed/10_benchmark_indices_cleaned.csv", index=False)